In [25]:
import win32api, win32con, win32gui
import ctypes
import pygetwindow as gw
from PIL import Image, ImageGrab
import cv2
import numpy as np
import pandas as pd
import pyautogui
from functions import *
import time
from random import randrange

In [74]:
window_size, window_top_left = obtain_window_info()
im = take_snippet(window_size,  window_top_left)
tile_number = convert_to_numbers(im)

In [75]:
unrevealed_tile = np.where(tile_number == 9)

In [89]:
linked_groups = [] # list of lists, with each inner list representing the index of the relevant numbered tile
# tile index starts with 0

# search through unrevealed_tiles to find the linked groups
for i in range(len(unrevealed_tile[0])):
    square = tile_number[unrevealed_tile[0][i]-1:unrevealed_tile[0][i]+2,
                         unrevealed_tile[1][i]-1:unrevealed_tile[1][i]+2
                        ]
    neighbor_nbr_tile = np.where((square >= 1) & (square <= 8))

    if len(neighbor_nbr_tile[0]) > 1:
        linked_group = []
        index_i = unrevealed_tile[0][i] * tile_number.shape[1] + unrevealed_tile[1][i]
        for j in range(len(neighbor_nbr_tile[0])):
            index_j = ((neighbor_nbr_tile[0][j] - 1) * tile_number.shape[1]) + \
                      (neighbor_nbr_tile[1][j] - 1) + index_i
            linked_group.append(index_j)
        linked_groups.append(linked_group)

In [111]:
# process the linked groups to get the exhausted linked pairs
linked_pairs = []
for i in linked_groups:
    if len(i) == 2:
        if i not in linked_pairs:
            linked_pairs.append(i)
    if len(i) > 2:
        for j in itertools.combinations(i, L):
            k = [j[0], j[1]]
            if k not in linked_pairs:
                linked_pairs.append(k)

In [112]:
linked_pairs

[[265, 266],
 [266, 267],
 [266, 268],
 [267, 268],
 [267, 269],
 [268, 269],
 [269, 270],
 [269, 271],
 [270, 271],
 [261, 293],
 [272, 304],
 [293, 325],
 [293, 357],
 [325, 357],
 [304, 336],
 [336, 367],
 [336, 399],
 [367, 399],
 [389, 421],
 [399, 431],
 [421, 422],
 [421, 487],
 [422, 487],
 [487, 519],
 [494, 526]]

In [104]:
linked_pairs

[[265, 266],
 [266, 267],
 [266, 268],
 [267, 268],
 [267, 268],
 [267, 269],
 [268, 269],
 [269, 270],
 [269, 271],
 [270, 271],
 [261, 293],
 [272, 304],
 [293, 325],
 [293, 357],
 [325, 357],
 [304, 336],
 [336, 367],
 [336, 399],
 [367, 399],
 [389, 421],
 [399, 431],
 [421, 422],
 [421, 487],
 [422, 487],
 [487, 519],
 [494, 526]]

In [101]:
import itertools

stuff = [1, 2, 3]
L = 2
for subset in itertools.combinations(stuff, L):
    print(type(subset))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [100]:
itertools.combinations(stuff, L)

In [90]:
linked_groups

[[265, 266],
 [266, 267, 268],
 [267, 268, 269],
 [269, 270, 271],
 [261, 293],
 [272, 304],
 [293, 325, 357],
 [304, 336],
 [336, 367, 399],
 [389, 421],
 [399, 431],
 [421, 422, 487],
 [487, 519],
 [494, 526]]

In [59]:
square[0][j]

9.0

In [63]:
print(neighbor_nbr_tile[0][j])
print(neighbor_nbr_tile[1][j])

2
2


In [73]:
print(unrevealed_tile[0][153])
print(unrevealed_tile[1][153])

7
11


In [55]:
tile_number[unrevealed_tile[0][i], unrevealed_tile[1][i]]

9.0

In [69]:
i = 233
print(unrevealed_tile[0][i])
print(unrevealed_tile[1][i])

12
28


In [71]:
square

array([[12.,  9., 12.],
       [ 9.,  9., 12.],
       [10., 10., 10.]])

In [70]:
neighbor_nbr_tile

(array([], dtype=int64), array([], dtype=int64))

In [45]:
cashed_list

[[152, 0],
 [152, 1],
 [153, 0],
 [153, 1],
 [153, 2],
 [154, 0],
 [154, 1],
 [154, 2],
 [155, 0],
 [155, 1],
 [155, 2],
 [165, 0],
 [165, 1],
 [166, 0],
 [166, 1],
 [194, 0],
 [194, 1],
 [194, 2],
 [195, 0],
 [195, 1],
 [211, 0],
 [211, 1],
 [211, 2],
 [239, 0],
 [239, 1],
 [240, 0],
 [240, 1],
 [256, 0],
 [256, 1],
 [256, 2],
 [273, 0],
 [273, 1],
 [274, 0],
 [274, 1]]

In [53]:
tile_number.shape[1]

32

In [29]:
i = 152
square = tile_number[unrevealed_tile[0][i]-1:unrevealed_tile[0][i]+2,
                         unrevealed_tile[1][i]-1:unrevealed_tile[1][i]+2
                        ]


In [30]:
square

array([[ 9.,  9.,  9.],
       [12.,  9., 12.],
       [11.,  3.,  1.]])

In [14]:
len(np.where((square >= 1) & (square <= 8))[0])

9

In [22]:
tile_number

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10.],
       [10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9., 10.],
       [10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9., 10.],
       [10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9., 10.],
       [10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         9.,  9.,  9.,  9.,  9., 10.],
       [10.,  9.,  9.,  2.,  2.,  3.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
  

In [21]:
tile_number[unrevealed_tile[0][92], unrevealed_tile[1][92]]

9.0

In [18]:
unrevealed_tile[1][92]

3

In [19]:
unrevealed_tile

(array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,
         9, 